# Generated by Django 3.1 on 2021-06-04 12:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210602_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categary',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('publish', 'Опубликован'), ('draft', 'Черновик')], max_length=15),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
